# Generated by Django 2.2.6 on 2019-10-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=9999)),
                ('article_text', models.TextField()),
                ('article_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editors_name', models.CharField(max_length=100)),
                ('editors_surname', models.CharField(max_length=100)),
                ('editor_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
