# Generated by Django 2.2.6 on 2019-10-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_News_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=9999)),
                ('blog_text', models.TextField()),
                ('blog_date', models.DateTimeField(verbose_name='date published')),
                ('blog_author', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=9999)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=9999)),
                ('thread_text', models.TextField()),
                ('thread_date', models.DateTimeField(verbose_name='date published')),
                ('thread_author', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_surname', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
