# Generated by Django 2.2.6 on 2019-10-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_News_App', '0002_blog_comment_thread_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
