# Generated by Django 2.2.6 on 2019-10-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_News_App', '0003_auto_20191101_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_id',
            new_name='article_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
