# Generated by Django 2.2.6 on 2019-11-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_News_App', '0004_auto_20191101_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='editor_id',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
