# Generated by Django 2.2.6 on 2019-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_News_App', '0002_auto_20191107_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='game_text',
            field=models.TextField(default=''),
        ),
    ]
