# Generated by Django 2.2.6 on 2019-11-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_News_App', '0003_gamepage_game_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePage',
            new_name='Game',
        ),
    ]
