# Generated by Django 2.2.6 on 2019-11-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=1000)),
                ('game_developer', models.CharField(max_length=1000)),
                ('game_text', models.TextField(default='')),
                ('game_publisher', models.CharField(max_length=1000)),
                ('game_rd', models.DateField(verbose_name='date published')),
                ('game_rating', models.FloatField(default=0.0)),
                ('game_img', models.ImageField(upload_to='photos', verbose_name='My Photo')),
            ],
        ),
    ]
