# Generated by Django 2.2.6 on 2019-12-06 19:22

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=1000)),
                ('game_developer', models.CharField(max_length=1000)),
                ('game_text', models.TextField(default='')),
                ('game_publisher', models.CharField(max_length=1000)),
                ('game_platforms', multiselectfield.db.fields.MultiSelectField(choices=[('PC', 'PC'), ('Xbox One', 'Xbox One'), ('PlayStation 4', 'PlayStation 4'), ('Nintendo Switch', 'Nintendo Switch'), ('PlayStation 3', 'PlayStation 3'), ('Wii U', 'Wii U'), ('Xbox 360', 'Xbox 360'), ('3DS', '3DS'), ('PlayStation Vita', 'PlayStation Vita')], default=None, max_length=91)),
                ('game_genre', multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('FPS', 'FPS'), ('Strategy', 'Strategy'), ('Shooter', 'Shooter'), ('Platformer', 'Platformer'), ('Fighting', 'Fighting'), ("Beat 'em up", "Beat 'em up"), ('Stealth', 'Stealth'), ('Survival', 'Survival'), ('Battle Royale', 'Battle Royale'), ('Rhythm games', 'Rhythm games'), ('Survival horror', 'Survival horror'), ('Metroidvania', 'Metroidvania'), ('Visual novels', 'Visual novels'), ('Interactive movie', 'Interactive movie'), ('Action RPG', 'Action RPG'), ('RPG', 'RPG'), ('JRPG', 'JRPG'), ('MMORPG', 'MMORPG'), ('Quest', 'Quest'), ('Roguelikes', 'Roguelikes'), ('Simulator', 'Simulator'), ('Strategy', 'Strategy'), ('MOBA', 'MOBA'), ('RTS', 'RTS'), ('Tower defense', 'Tower defense'), ('TBS', 'TBS'), ('Sports', 'Sports'), ('Racing', 'Racing'), ('MMO', 'MMO'), ('Soulslike', 'Soulslike'), ('Sandbox', 'Sandbox'), ('Adventure', 'Adventure'), ('Hack and slash', 'Hack and slash')], default=None, max_length=315)),
                ('game_rd', models.DateField(verbose_name='date published')),
                ('game_age_rating', multiselectfield.db.fields.MultiSelectField(choices=[('E', 'E'), ('E 10+', 'E 10+'), ('T', 'T'), ('M', 'M'), ('A', 'A')], default=None, max_length=13)),
                ('game_img', models.ImageField(default=None, null=True, upload_to='game_img/')),
                ('game_trailer', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_pages.Game')),
            ],
        ),
    ]
