# Generated by Django 2.2.6 on 2019-12-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0003_game_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_score',
            field=models.FloatField(default=0.0),
        ),
    ]
