# Generated by Django 2.2.6 on 2019-11-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0003_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.ImageField(default=None, null=True, upload_to='game_img/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_trailer',
            field=models.URLField(default=None, null=True),
        ),
    ]
