# Generated by Django 2.2.6 on 2019-11-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0004_auto_20191129_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='game_img/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_trailer',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
