# Generated by Django 2.2.6 on 2019-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0005_auto_20191129_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.ImageField(default=None, null=True, upload_to='game_img/'),
        ),
    ]
