# Generated by Django 2.2.6 on 2019-11-29 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_pages', '0006_auto_20191129_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
