# Generated by Django 2.2.6 on 2019-11-29 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0007_auto_20191129_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
