# Generated by Django 2.2.6 on 2019-12-04 18:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0008_auto_20191129_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('FPS', 'FPS'), ('Strategy', 'Strategy'), ('Shooter', 'Shooter'), ('Platformer', 'Platformer'), ('Fighting', 'Fighting'), ("Beat 'em up", "Beat 'em up"), ('Stealth', 'Stealth'), ('Survival', 'Survival'), ('Battle Royale', 'Battle Royale'), ('Rhythm games', 'Rhythm games'), ('Survival horror', 'Survival horror'), ('Metroidvania', 'Metroidvania'), ('Visual novels', 'Visual novels'), ('Interactive movie', 'Interactive movie'), ('Action RPG', 'Action RPG'), ('MMORPG', 'MMORPG'), ('Roguelikes', 'Roguelikes'), ('Simulator', 'Simulator'), ('Strategy', 'Strategy'), ('MOBA', 'MOBA'), ('RTS', 'RTS'), ('Tower defense', 'Tower defense'), ('TBS', 'TBS'), ('Sports', 'Sports'), ('Racing', 'Racing'), ('MMO', 'MMO'), ('Soulslike', 'Soulslike')], default=None, max_length=267),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PC', 'PC'), ('Xbox One', 'Xbox One'), ('PS4', 'PS4'), ('Nintendo Switch', 'Nintendo Switch'), ('PS3', 'PS3'), ('Wii U', 'Wii U')], default=None, max_length=41),
        ),
    ]
