# Generated by Django 2.2.6 on 2019-12-05 15:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0009_auto_20191205_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_rating',
            new_name='game_score',
        ),
        migrations.AddField(
            model_name='game',
            name='game_age_rating',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('E', 'E'), ('E 10+', 'E 10+'), ('T', 'T'), ('M', 'M'), ('A', 'A')], default=None, max_length=13),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PC', 'PC'), ('Xbox One', 'Xbox One'), ('PlayStation 4', 'PlayStation 4'), ('Nintendo Switch', 'Nintendo Switch'), ('PlayStation 3', 'PlayStation 3'), ('Wii U', 'Wii U'), ('Xbox 360', 'Xbox 360'), ('3DS', '3DS'), ('PlayStation Vita', 'PlayStation Vita')], default=None, max_length=91),
        ),
    ]
