# Generated by Django 2.2.6 on 2019-12-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0011_auto_20191206_1335'),
        ('game_pages', '0011_auto_20191206_1248'),
    ]

    operations = [
    ]
