# Generated by Django 2.2.6 on 2019-11-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImg',
            field=models.ImageField(default='NULL', upload_to='user_avas/'),
        ),
    ]
