# Generated by Django 2.2.6 on 2019-12-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=1000)),
                ('article_text', models.TextField(default='')),
                ('article_date', models.DateTimeField(auto_now_add=True)),
                ('article_score', models.FloatField(default=0.0)),
                ('numberOfClicks', models.IntegerField(default=0)),
                ('article_img', models.ImageField(default='NULL', upload_to='article_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=1000)),
                ('blog_text', models.TextField(default='')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_score', models.FloatField(default=0.0)),
                ('numberOfClicks', models.IntegerField(default=0)),
                ('blog_img', models.ImageField(default='NULL', upload_to='blog_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LikeSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_name', models.CharField(max_length=1000)),
                ('thread_text', models.TextField()),
                ('thread_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
