# Generated by Django 2.2.7 on 2019-11-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0001_initial'),
        ('article_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='game_developer',
        ),
        migrations.RemoveField(
            model_name='article',
            name='game_platforms',
        ),
        migrations.RemoveField(
            model_name='article',
            name='game_publisher',
        ),
        migrations.AddField(
            model_name='article',
            name='game_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_pages.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='isBlog',
            field=models.BooleanField(default=False, verbose_name=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='numberOfClicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_pages.Article')),
            ],
        ),
    ]
