# Generated by Django 2.2.6 on 2019-12-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_pages', '0001_initial'),
        ('game_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_pages.Game'),
        ),
    ]
