# Generated by Django 2.2.6 on 2019-12-06 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_pages', '0003_auto_20191207_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
