# Generated by Django 2.2.6 on 2019-12-06 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_pages', '0011_auto_20191206_1335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_pages', '0004_article_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='game_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_pages.Game'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.CreateModel(
            name='LikeSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_pages.Comment')),
                ('likes', models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=1000)),
                ('blog_text', models.TextField(default='')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_rating', models.FloatField(default=0.0)),
                ('numberOfClicks', models.IntegerField(default=0)),
                ('isBlog', models.BooleanField(default=True)),
                ('blog_img', models.ImageField(default='NULL', upload_to='blog_img/')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_pages.Game')),
            ],
        ),
    ]
