# Generated by Django 2.2.6 on 2019-12-07 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_pages', '0004_auto_20191207_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
