# Generated by Django 2.2.6 on 2019-12-06 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_pages', '0005_auto_20191206_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
