# Generated by Django 2.2.6 on 2019-12-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_pages', '0005_auto_20191206_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='rating',
            new_name='article_score',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_rating',
            new_name='blog_score',
        ),
        migrations.RemoveField(
            model_name='article',
            name='isBlog',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='isBlog',
        ),
    ]
