# Generated by Django 2.2.6 on 2019-12-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_pages', '0006_auto_20191208_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_pages.Blogs'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_pages.Thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_score',
        ),
        migrations.AddField(
            model_name='article',
            name='article_score',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='article_raters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_score',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_score',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='blog_raters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_pages.Article'),
        ),
    ]
