# Generated by Django 2.2.6 on 2019-12-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_pages', '0006_auto_20191206_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_pages.Game'),
        ),
    ]
