# Generated by Django 2.2.6 on 2019-12-08 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_pages', '0007_auto_20191208_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='comment_raters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeSystem',
        ),
    ]
