# Generated by Django 2.2.6 on 2019-12-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_pages', '0008_auto_20191208_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='upvotes',
            new_name='upvoters',
        ),
    ]
